version: '3.3'
services:
  ponto-app:
    build: .
    ports:
      - "8181:80"
      #      para não matar minha mudança ao dar docker compose down
    volumes:
      - ./:/usr/share/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    #      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  mysql-app:
    image: mysql:8.0.27
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: "rb_simplificado"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
