<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;
use OwenIt\Auditing\Auditable as AuditableTrait;

class Collapse extends Model implements Auditable
{
    use HasFactory;
    use AuditableTrait;

    protected $table = 'collapses';
    protected $fillable = [
        'cargo_id',
        'nome',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($collapse) {
            $collapse->campos()->delete();
        });
    }

    public function campos()
    {
        return $this->hasMany(Campo::class, 'collapse_id', 'id');
    }

    public function cargo()
    {
        return $this->belongsTo(Cargo::class, 'cargo_id', 'id');
    }
}
